default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index"}
    methods: GET
    
default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas"}
    methods: POST
    
default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login"}
    methods: POST
    
user_new:
    path: /user/new
    defaults: { _controller: "AppBundle:User:new"}
    methods: POST

user_edit:
    path: /user/edit
    defaults: { _controller: "AppBundle:User:edit"}
    methods: POST
    
task_new:
    path: /task/new
    defaults: { _controller: "AppBundle:Task:new"}
    methods: POST

# id, identificador que se pasa por url, por defecto null
task_edit:
    path: /task/edit/{id}
    defaults: { _controller: "AppBundle:Task:edit", id: null}
    methods: POST
    
tasks_list:
    path: /task/list
    defaults: { _controller: "AppBundle:Task:tasks"}
    methods: POST
    
tasks_detail:
    path: /task/detail/{id}
    defaults: { _controller: "AppBundle:Task:task", id:null}
    methods: POST
    
task_search:
    path: /task/search/{search}
    defaults: { _controller: "AppBundle:Task:search", search:null}
    methods: POST
    
task_remove:
    path: /task/remove/{id}
    defaults: { _controller: "AppBundle:Task:remove", id:null}
    methods: POST