default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index"}
    methods: GET
    
default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas"}
    methods: POST
    
default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login"}
    methods: POST
    
user_new:
    path: /user/new
    defaults: { _controller: "AppBundle:User:new"}
    methods: POST

user_edir:
    path: /user/edit
    defaults: { _controller: "AppBundle:User:edit"}
    methods: POST
    
task_new:
    path: /task/new
    defaults: { _controller: "AppBundle:Task:new"}
    methods: POST